spring.application.name=moviedb

spring.datasource.url=jdbc:postgresql://zephyr.proxy.rlwy.net:46520/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=fUtDELRyRjKsArBqTvTpKbMSidUrBMUQ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}